spring:
  datasource:    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: platzi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
           non_contextual_creation: true 
  security:
   user:
    name: vega
    password: platzi